{{- if .Values.testbot.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xrengine.testbot.fullname" . }}
  labels:
    {{- include "xrengine.testbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.testbot.replicaCount }}
  selector:
    matchLabels:
      {{- include "xrengine.testbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xrengine.testbot.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/test-bot-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.testbot.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "xrengine.testbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.testbot.podSecurityContext | nindent 8 }}
      {{- $releaseName := .Release.Name }}
      {{ if not (empty .Values.release) }}
      {{- $releaseName = .Values.release.name | default .Release.Name }}
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.testbot.securityContext | nindent 12 }}
          image: "{{ .Values.testbot.image.repository }}:{{ .Values.testbot.image.tag }}"
          imagePullPolicy: {{ .Values.testbot.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "xrengine.testbot.fullname" . }}
                optional: true
          env:
            - name: SERVER_MODE
              value: "client"
            - name: KUBERNETES
              value: "true"
            - name: MYSQL_USER
              value: {{ .Values.mariadb.db.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.db.name }}
            - name: MYSQL_PASSWORD
              {{- if not .Values.mariadb.enabled }}
              value: {{ .Values.mariadb.db.password | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.existingSecret }}
                  name: {{ .Values.mariadb.existingSecret }}
                  {{- else }}
                  name: {{ template "xrengine.mariadb.fullname" . }}
                  {{- end }}
                  key: mariadb-password
              {{- end }}
            - name: MYSQL_HOST
              value: {{ template "xrengine.mariadb.host" . }}
            - name: MYSQL_PORT
              value: {{ .Values.mariadb.externalPort | quote }}
            - name: RELEASE_NAME
              value: {{ $releaseName }}
          # ports:
          #   - name: http
          #     containerPort: 3000
          #     protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.testbot.resources | nindent 12 }}
      {{- with .Values.testbot.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.testbot.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.testbot.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
